# Generated by Django 6.0 on 2025-12-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0002_rename_note_entries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entries',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='entries',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='entries',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
