# Generated by Django 6.0 on 2025-12-11 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import notes.models

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='add_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='add_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='add_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='add_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='add_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='add_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='short_description',
        ),
        migrations.AddField(
            model_name='links',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='bootstrap_icon_name',
            field=models.CharField(blank=True, default=notes.models.get_random_icon, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='bootstrap_icon_name',
            field=models.CharField(blank=True, default=notes.models.get_random_icon, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections',
                                    to='notes.topic'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
