# Generated by Django 6.0 on 2025-12-11 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_user_from_section(apps, schema_editor):
    Links = apps.get_model('notes', 'Links')
    for link in Links.objects.all():
        link.user = link.section.user
        link.save(update_fields=['user'])

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_article_options_alter_code_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_user_from_section, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='links',
            name='user',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
