# Generated by Django 6.0 on 2025-12-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_set_user_from_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
