# Generated by Django 6.0 on 2025-12-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_links_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_title',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
