# Generated by Django 6.0 on 2025-12-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_image_description_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
