# Generated by Django 6.0 on 2026-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_image_description_alter_links_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
