# Generated by Django 6.0 on 2025-12-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_taskcomment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'Active'), ('canceled', 'Canceled')], default='in_progress'),
        ),
    ]
