# Generated by Django 6.0 on 2026-02-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'Active'), ('canceled', 'Canceled'), ('is_planned', 'Planned')], default='in_progress'),
        ),
    ]
