# Generated by Django 6.0 on 2026-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
