# Generated by Django 5.2.9 on 2025-12-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_status_alter_task_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('end_date',)},
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
